### ISSUE TITLE
License and setup.py

### ISSUE THREAD

**Issue by jgarte** [jacksonrakena/migadu-cli#1]
Hi, what is the license on this project?

What do you think about adding a setup.py

The reason I ask is because I started packaging this cli for a custom guix channel so that I can use it.

wdyt?

Let me know if you'd like me to contribute the setup.py :)

**Comment by jacksonrakena** [comment]
This project is like most of mine - MIT. Drop a copy of the MIT License with a link to the repo and you’re all good.

I’d really appreciate a setup.py - maybe make a PR?
